-- ============================================================
-- 0005_rubric_improvements.sql
-- Auto-generated from seed/rubric_improvement_suggestions.csv by
-- seed/apply_rubric_improvements.mjs.  Safe to re-run.
--
-- Updates teacher_next_moves / coaching_considerations / resources /
-- feedback_starter for B.d (L2,L3), B.e (L3), and E.c (L1,L2) only.
-- All other rubric cells are untouched.
-- ============================================================

-- B.d level 2 — Improvement Necessary
UPDATE pedagogy_library SET teacher_next_moves = '["Replace discipline lectures with explicit teaching of SEL skills using modeling and role-play","incorporate a daily 5‑minute SEL routine (e.g., morning meeting) to practice specific social skills","co-plan SEL integration with a colleague and observe their implementation"]', coaching_considerations = '["Provide the teacher with resources on CASEL SEL competencies and model a morning meeting. Observe a lesson, then debrief using student evidence to identify growth and adjust routines","encourage peer observation for feedback"]', resources = '[{"title":"CASEL. (2020). SEL integrated instruction toolkit","source":"CASEL. (2020). SEL integrated instruction toolkit","type":"reading"},{"title":"Responsive Classroom. (n.d.). Morning meeting guide.","source":"Responsive Classroom. (n.d.). Morning meeting guide.","type":"reading"}]', feedback_starter = 'When you taught _____, how did you explicitly model and practice the target social skill?', updated_at = CURRENT_TIMESTAMP WHERE indicator_id = 14 AND level = 2;

-- B.d level 3 — Effective
UPDATE pedagogy_library SET teacher_next_moves = '["Maintain weekly SEL mini-lessons and integrate social skill instruction into academic content","collaborate with grade-level team to share effective SEL strategies","invite students to co-create class norms and reflect on social skill growth"]', coaching_considerations = '["During observations, note how the teacher weaves SEL language into academic discussions","ask the teacher to share one successful SEL integration during PLCs","challenge them to mentor a colleague on SEL routines"]', resources = '[{"title":"Jones, S. et al. (2017). Social and emotional learning in schools: A guide to integrating with academics","source":"Jones, S. et al. (2017). Social and emotional learning in schools: A guide to integrating with academics","type":"reading"},{"title":"Panorama Education. (n.d.). SEL activities and strategies.","source":"Panorama Education. (n.d.). SEL activities and strategies.","type":"reading"}]', feedback_starter = 'What impact did integrating SEL into your academic lesson have on student engagement?', updated_at = CURRENT_TIMESTAMP WHERE indicator_id = 14 AND level = 3;

-- B.e level 3 — Effective
UPDATE pedagogy_library SET teacher_next_moves = '["Script and rehearse one routine each week (entry, transitions, materials) with student input","use visual anchor charts to remind students of routine steps","collect data on transition times and aim to reduce them by 10–15%","invite a peer to observe and provide feedback"]', coaching_considerations = '["Model a routine rehearsal with the teacher, demonstrating clear expectations and positive reinforcement","provide transition timing tool","review data with the teacher and celebrate gains","encourage sharing of routine scripts at PLCs"]', resources = '[{"title":"Lemov, D. (2021). Teach Like a Champion 3.0—Technique 30: Tight Transitions","source":"Lemov, D. (2021). Teach Like a Champion 3.0—Technique 30: Tight Transitions","type":"reading"},{"title":"New Teachers Center. (n.d.). Effective classroom routines guide.","source":"New Teachers Center. (n.d.). Effective classroom routines guide.","type":"reading"}]', feedback_starter = 'How did practicing the new routine with students influence transition smoothness?', updated_at = CURRENT_TIMESTAMP WHERE indicator_id = 15 AND level = 3;

-- E.c level 1 — Does Not Meet
UPDATE pedagogy_library SET teacher_next_moves = '["Before each unit, send a concise overview to families outlining learning goals, essential vocabulary and success criteria","include questions parents can ask to support learning","ensure communications are translated and accessible","plan a personal introductory phone call or message to build rapport"]', coaching_considerations = '["Provide a template for unit overviews that includes learning targets and support tips","role-play a parent phone call with the teacher","review a draft communication for clarity and cultural responsiveness"]', resources = '[{"title":"Epstein, J. et al. (2019). School, Family, and Community Partnerships","source":"Epstein, J. et al. (2019). School, Family, and Community Partnerships","type":"reading"},{"title":"Harvard Family Research Project. (2016). Tips for communicating student progress.","source":"Harvard Family Research Project. (2016). Tips for communicating student progress.","type":"reading"}]', feedback_starter = 'How will you ensure families understand your unit’s expectations and can support their child’s learning?', updated_at = CURRENT_TIMESTAMP WHERE indicator_id = 43 AND level = 1;

-- E.c level 2 — Improvement Necessary
UPDATE pedagogy_library SET teacher_next_moves = '["Develop a parent-friendly curriculum guide for the semester that explains units, key assignments, and rubrics","share exemplar student work samples with commentary to illustrate proficiency","host a virtual or in-person curriculum night to explain expectations and answer questions"]', coaching_considerations = '["Review the guide with the teacher and ensure it uses plain language and examples","co-plan the curriculum night agenda focusing on interactive discussion","gather parent feedback after the event for continuous improvement"]', resources = '[{"title":"National PTA. (2020). Standards for family-school partnerships","source":"National PTA. (2020). Standards for family-school partnerships","type":"reading"},{"title":"Great Schools Partnership. (2017). Communicating learning goals to families.","source":"Great Schools Partnership. (2017). Communicating learning goals to families.","type":"reading"}]', feedback_starter = 'What strategies will you use to make curriculum information engaging and understandable for families?', updated_at = CURRENT_TIMESTAMP WHERE indicator_id = 43 AND level = 2;

-- 5 rows updated.
